### ISSUE TITLE
Conexión a Base de datos & DAO's

### ISSUE THREAD

**Issue by Ikero12** [Ikero12/Hospitalex_Ikero#1]
Realizar la conexión a la base de datos y los DAO's respectivamente.

**Comment by AlexFerMar** [comment]
¡Hola Iker!

Ya he empezado con la tarea asignada. Solo me quedan algunas clases DAO por hacer. 

Buenas noches.

**Comment by AlexFerMar** [comment]
¡Hola!

Ya he terminado los DAO. Haré algunas pruebas para asegurarme de que las consultas están correctamente y, en caso de que todo este bien, te mandaré un pull request y cerraré el issue. 

Buenas tardes.

**Comment by Ikero12** [comment]
Hola muy buenas :)

Ya vi el trabajo y ya hice el pull request. Muchas gracias por avisar. 

Un saludo!
