### ISSUE TITLE
Mostrar tabla citas

### ISSUE THREAD

**Issue by AlexFerMar** [Ikero12/Hospitalex_Ikero#11]
Mostrar una tabla con las citas y sus datos. Ha de distinguir entre pacientes y médicos y solo mostrar sus citas.  En ambos casos se dividiran en dos tablas: 

- Citas activas

- Citas pasadas

**Comment by Ikero12** [comment]
Hola Alex,

Ya está implementado el método para crear las tablas solicitadas y también introducida en las respectivas pestañas. Gracias por tu trabajo ha sido un honor sir Alex.

Saludos,
Erik
