### ISSUE TITLE
Interfaz del Programa

### ISSUE THREAD

**Issue by AlexFerMar** [Ikero12/Hospitalex_Ikero#2]
Necesitamos la pantalla de inicio de sesión y de usuarios.

**Comment by Ikero12** [comment]
¡Buenas noches!

La pantalla de inicio de sesión ya está finiquitada. En breves programaré la pantalla de médicos, enfermeros y pacientes, en ese especifico orden. 

Un cordial saludo,
Iker

**Comment by Ikero12** [comment]
Estimado Sr. Fernández,

Ya he finalizado la programación de las interfaces como me has pedido. Estoy a su disposición para cualquier otro trabajo. 

Espero poder ayudarte en una futura ocasión y que sea usted saludado cordialmente,
Iker.

**Comment by AlexFerMar** [comment]
Hola Sr. Erik,

Hay una fina línea entre la cordialidad y la pedantería. Si vamos a trabajar juntos espero se lo tome usted más en serio. Dicho esto, buen código.

Saludos,
Alex
