### ISSUE TITLE
Crear un aviso en la interfaz

### ISSUE THREAD

**Issue by AlexFerMar** [Ikero12/Hospitalex_Ikero#6]
¡Hola Iker!

Estoy programando la lógica de inicio de sesión y me gustaría preguntarte si podrías añadir una sección en el Log In que avise al usuario por qué no pudo iniciar sesión. 

Muchas Gracias.

**Comment by Ikero12** [comment]
¡Hola!

Ya he añadido el Label. Ahora solo falta implementarlo para que sea triggereado que ya queda en tus manos. Cualquier cosa me comentas, cierro el issue aquí.

Un cordial saludo,
Iker.
