### ISSUE TITLE
Implementar usuarios al menu

### ISSUE THREAD

**Issue by AlexFerMar** [Ikero12/Hospitalex_Ikero#9]
Hola Iker!

Ya he añadido la capacidad de "iniciar sesión" en el programa y parcheado un pequeño error. Me  gustaría pedirte que implementases los datos de los usuarios  a los disyuntos menús. Estas funcionalidades se están añadiendo a la rama GUI_inicioSesion.

Saludos,
Alex

**Comment by Ikero12** [comment]
Hola Alex,

Gracias por la implementación. Mañana ya me pongo a programar la interfaz con los datos del usuario que inició sesión, además del botón para "desconectar". 

Saludos del mejor compañero de trabajo, 
Iker

**Comment by Ikero12** [comment]
Hola Alex!

Ya he acabado con la implementación de la información personalizada de los usuarios al conectarse. También he implementado un botón de desconexión con un pequeño mensaje de advertencia.

Saludos,
Iker.

**Comment by AlexFerMar** [comment]
¡Hola Iker!

¡Ya veo que has juntado ambas partes, muchas gracias por la ayuda!

Saludos,
Alex
